### ISSUE TITLE
appears to be hanging after upgrade ...

### ISSUE THREAD

**Issue by tansaku** [makersacademy/toolbelt#16]
```
[tansaku@Samuels-MacBook-Pro:~/Documents/Github/MakersAcademy/rps-challenge (master)]$ 
→ makers fetch_pull_requests -a
fetching open pull requests from makersacademy/rps-challenge...
Enter your github username: tansaku
Enter GitHub password for tansaku: fetching closed pull requests from makersacademy/rps-challenge...


```

**Comment by tansaku** [comment]
just tried this again - worked fine for pulling down open pull requests on bowling challenge, but hangs trying to pull down closed pull requests:

```
[tansaku@Samuels-MBP-2:~/Documents/Github/MakersAcademy/bowling-challenge (master)]$ 
→ makers fetch_pull_requests -c
fetching closed pull requests from makersacademy/bowling-challenge...
```

is it because I may have some of these remotes existing already?  Or something specific to closed pull requests?

Ctrl-Cing it breaks it here but not sure if that's relevant:

```
^C/Users/tansaku/.rvm/gems/ruby-2.2.3/gems/json-1.8.3/lib/json/common.rb:155:in `parse': Interrupt
    from /Users/tansaku/.rvm/gems/ruby-2.2.3/gems/multi_json-1.11.2/lib/multi_json/adapters/json_common.rb:14:in `load'
    from /Users/tansaku/.rvm/gems/ruby-2.2.3/gems/multi_json-1.11.2/lib/multi_json/adapter.rb:21:in `load'
    from /Users/tansaku/.rvm/gems/ruby-2.2.3/gems/multi_json-1.11.2/lib/multi_json.rb:119:in `load'
    from /Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sawyer-0.6.0/lib/sawyer/serializer.rb:62:in `call'
    from /Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sawyer-0.6.0/lib/sawyer/serializer.rb:62:in `decode'
    from /Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sawyer-0.6.0/lib/sawyer/agent.rb:125:in `decode_body'
    from /Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sawyer-0.6.0/lib/sawyer/response.rb:18:in `initialize'
    from /Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sawyer-0.6.0/lib/sawyer/agent.rb:107:in `new'
    from /Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sawyer-0.6.0/lib/sawyer/agent.rb:107:in `call'
    from /Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sawyer-0.6.0/lib/sawyer/relation.rb:264:in `call'
    from /Users/tansaku/.rvm/gems/ruby-2.2.3/gems/sawyer-0.6.0/lib/sawyer/relation.rb:163:in `get'
    from /Users/tansaku/.rvm/gems/ruby-2.2.3/gems/makers_toolbelt-0.0.8/lib/makers_toolbelt/fetch_pull_requests.rb:74:in `fetch_more_pages'
    from /Users/tansaku/.rvm/gems/ruby-2.2.3/gems/makers_toolbelt-0.0.8/lib/makers_toolbelt/fetch_pull_requests.rb:65:in `fetch_pull_requests'
    from /Users/tansaku/.rvm/gems/ruby-2.2.3/gems/makers_toolbelt-0.0.8/lib/makers_toolbelt/fetch_pull_requests.rb:60:in `closed_pull_requests'
    from /Users/tansaku/.rvm/gems/ruby-2.2.3/gems/makers_toolbelt-0.0.8/lib/makers_toolbelt/fetch_pull_requests.rb:20:in `run'
    from /Users/tansaku/.rvm/gems/ruby-2.2.3/gems/makers_toolbelt-0.0.8/bin/makers:19:in `run'
    from /Users/tansaku/.rvm/gems/ruby-2.2.3/gems/makers_toolbelt-0.0.8/bin/makers:34:in `<top (required)>'
    from /Users/tansaku/.rvm/gems/ruby-2.2.3/bin/makers:23:in `load'
    from /Users/tansaku/.rvm/gems/ruby-2.2.3/bin/makers:23:in `<main>'
    from /Users/tansaku/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
    from /Users/tansaku/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by silvabox** [comment]
This was caused by a non-terminating `while` statement

**Comment by silvabox** [comment]
`gem update makers_toolbelt` to fix
