### ISSUE TITLE
Generate pairs should work with odd-numbered lists

### ISSUE THREAD

**Issue by rai-hi** [makersacademy/toolbelt#27]
When a list with an odd number of members is provided to `generate_pairs`, an error is thrown:

```
Traceback (most recent call last):
    9: from /Users/leoht/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
    8: from /Users/leoht/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
    7: from /Users/leoht/.rvm/gems/ruby-2.6.5/bin/makers:23:in `<main>'
    6: from /Users/leoht/.rvm/gems/ruby-2.6.5/bin/makers:23:in `load'
    5: from /Users/leoht/.rvm/gems/ruby-2.6.5/gems/makers_toolbelt-0.2.1/bin/makers:34:in `<top (required)>'
    4: from /Users/leoht/.rvm/gems/ruby-2.6.5/gems/makers_toolbelt-0.2.1/bin/makers:19:in `run'
    3: from /Users/leoht/.rvm/gems/ruby-2.6.5/gems/makers_toolbelt-0.2.1/lib/makers_toolbelt/generate_pairs.rb:19:in `run'
    2: from /Users/leoht/.rvm/gems/ruby-2.6.5/gems/makers_toolbelt-0.2.1/lib/makers_toolbelt/generate_pairs.rb:19:in `open'
    1: from /Users/leoht/.rvm/gems/ruby-2.6.5/gems/makers_toolbelt-0.2.1/lib/makers_toolbelt/generate_pairs.rb:21:in `block in run'
/Users/leoht/.rvm/gems/ruby-2.6.5/gems/one_factorization-0.1.1/lib/one_factorization/array.rb:10:in `one_factorize': OneFactorization::InvalidLengthError (OneFactorization::InvalidLengthError)
```

... and no pairs file is generated. Instead, @leoht says we should pair the lone list member with a dummy list member 'Flying solo', so that Mechacoach can spit out a message like the following:

>mechacoach APP  11:15 AM
>@channel assignments for your next pairing session:
> @User1, @User2
>@Rainer Hind, Flying solo

**Comment by rai-hi** [comment]
Closed by #28
