### ISSUE TITLE
learn to program repo error

### ISSUE THREAD

**Issue by nikeshashar** [makersacademy/toolbelt#8]
```
  learn_to_program git:(master) makers fetch_pull_requests -a            
/Users/nikesh/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- octokit (LoadError)
    from /Users/nikesh/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/nikesh/.rvm/gems/ruby-2.1.5/gems/makers_toolbelt-0.0.5/lib/makers_toolbelt/fetch_pull_requests.rb:1:in `<top (required)>'
    from /Users/nikesh/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/nikesh/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/nikesh/.rvm/gems/ruby-2.1.5/gems/makers_toolbelt-0.0.5/lib/makers_toolbelt.rb:2:in `<top (required)>'
    from /Users/nikesh/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/nikesh/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/nikesh/.rvm/gems/ruby-2.1.5/gems/makers_toolbelt-0.0.5/bin/makers:3:in `<top (required)>'
    from /Users/nikesh/.rvm/gems/ruby-2.1.5/bin/makers:23:in `load'
    from /Users/nikesh/.rvm/gems/ruby-2.1.5/bin/makers:23:in `<main>'
    from /Users/nikesh/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
    from /Users/nikesh/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by nikeshashar** [comment]
Fixed this by installing Octokit

**Comment by nikeshashar** [comment]
And now getting 

```
➜  learn_to_program git:(master) makers fetch_pull_requests -a
fetching open pull requests from makersacademy/learn_to_program...
fetching closed pull requests from makersacademy/learn_to_program...
/Users/nikesh/.rvm/gems/ruby-2.1.5/gems/makers_toolbelt-0.0.5/lib/makers_toolbelt/fetch_pull_requests.rb:61:in `closed_pull_requests': undefined method `get' for nil:NilClass (NoMethodError)
    from /Users/nikesh/.rvm/gems/ruby-2.1.5/gems/makers_toolbelt-0.0.5/lib/makers_toolbelt/fetch_pull_requests.rb:20:in `run'
    from /Users/nikesh/.rvm/gems/ruby-2.1.5/gems/makers_toolbelt-0.0.5/bin/makers:19:in `run'
    from /Users/nikesh/.rvm/gems/ruby-2.1.5/gems/makers_toolbelt-0.0.5/bin/makers:34:in `<top (required)>'
    from /Users/nikesh/.rvm/gems/ruby-2.1.5/bin/makers:23:in `load'
    from /Users/nikesh/.rvm/gems/ruby-2.1.5/bin/makers:23:in `<main>'
    from /Users/nikesh/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
    from /Users/nikesh/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```
